'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function SignInPage(){
  const router=useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const r=await fetch('/api/auth/signin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to sign in');router.push('/dashboard')}catch(err){setError(err instanceof Error?err.message:'Unable to sign in')}finally{setLoading(false)}}
  return <main className="auth-wrap"><section className="auth-visual"><Link href="/" className="logo"><span className="logo-mark">L</span><span className="brand">Lumia<span className="gradient-text"> AI</span></span></Link><div><h1>Your business, with an AI employee.</h1><p>Stay close to customers, automate repetitive work and keep your sales operation moving from one calm workspace.</p></div><div className="auth-points"><div className="auth-point"><span className="check">✓</span> AI-powered customer conversations</div><div className="auth-point"><span className="check">✓</span> Products, orders and marketplace</div><div className="auth-point"><span className="check">✓</span> Built for WhatsApp and social commerce</div></div></section><section className="auth-panel"><div className="auth-box"><h2>Welcome back</h2><p className="lead">Sign in to your Lumia workspace.</p>{error&&<div className="form-error">{error}</div>}<form onSubmit={submit}><div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@business.com" required/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></div><button className="btn btn-primary auth-submit" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form><p className="auth-switch">New to Lumia? <Link href="/signup">Create an account</Link></p></div></section></main>
}
