'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

const nav=[['Overview','⌂'],['Conversations','◌'],['Customers','♙'],['Products','▦'],['Orders','◫'],['Knowledge','✦'],['Marketplace','◈'],['Channels','◎'],['Settings','⚙']];
const orders=[['#ORD-1048','Jean Claude','RWF 86,000','Delivered','green'],['#ORD-1047','Aline M.','RWF 52,000','Processing','blue'],['#ORD-1046','Eric N.','RWF 38,000','Pending','amber'],['#ORD-1045','Divine K.','RWF 91,000','Delivered','green']];
const products=[['Classic Sneakers','RWF 38,000','120 in stock','👟'],['Everyday Backpack','RWF 29,500','48 in stock','🎒'],['Minimal Watch','RWF 52,000','26 in stock','⌚'],['Lumia Hoodie','RWF 45,000','74 in stock','🧥'],['Travel Bottle','RWF 18,500','91 in stock','🥤'],['Desk Lamp','RWF 24,000','33 in stock','💡']];
export default function Dashboard(){const[active,setActive]=useState('Overview'),[open,setOpen]=useState(false),[user,setUser]=useState<any>(null),[business,setBusiness]=useState<any>(null);useEffect(()=>{Promise.all([fetch('/api/auth/me').then(r=>r.ok?r.json():null),fetch('/api/business').then(r=>r.ok?r.json():null)]).then(([u,b])=>{setUser(u?.user);setBusiness(b?.business)})},[]);return <div className="app"><aside className={`sidebar ${open?'open':''}`}><div className="sidebar-brand"><Link href="/" className="logo"><span className="logo-mark">L</span><span className="brand">Lumia<span className="gradient-text"> AI</span></span></Link></div><div className="workspace"><small>WORKSPACE</small><strong>{business?.name||'My Business'}</strong></div><div className="nav-section">Workspace</div><div className="nav-list">{nav.slice(0,6).map(([n,i])=><Nav key={n} n={n} i={i} active={active} setActive={setActive} close={()=>setOpen(false)}/>)}</div><div className="nav-section">Growth</div><div className="nav-list">{nav.slice(6).map(([n,i])=><Nav key={n} n={n} i={i} active={active} setActive={setActive} close={()=>setOpen(false)}/>)}</div><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{(user?.name||'LU').slice(0,2).toUpperCase()}</div><div><b style={{fontSize:12}}>{user?.name||'Lumia User'}</b><small>{user?.email||'Signed in'}</small></div></div></div></aside><div className="main"><header className="topbar"><div className="top-actions"><button className="icon-btn mobile-menu" onClick={()=>setOpen(v=>!v)}>☰</button><span className="top-title">{active}</span></div><div className="top-actions"><button className="icon-btn">⌕</button><button className="icon-btn">♢</button><Link href="/" className="btn btn-soft">Website</Link></div></header><main className="page">{active==='Overview'?<Overview/>:active==='Products'?<Products/>:active==='Orders'?<Orders/>:active==='Channels'?<Channels/>:active==='Settings'?<Settings name={business?.name||''}/>:<Placeholder title={active}/>}</main></div></div>}
function Nav({n,i,active,setActive,close}:any){return <button onClick={()=>{setActive(n);close()}} className={`nav-item ${active===n?'active':''}`}><span className="nav-icon">{i}</span>{n}</button>}
function Overview(){return <><div className="page-head"><div><h1>Good evening 👋</h1><p>Here is what is happening across your business today.</p></div><button className="btn btn-primary">+ New conversation</button></div><div className="stat-grid"><Stat l="AI conversations" v="1,284" m="+18.4% this month"/><Stat l="Customers" v="846" m="+12.7% this month"/><Stat l="Orders" v="186" m="+9.3% this month"/><Stat l="Revenue" v="4.82M" m="+21.6% this month"/></div><div className="content-grid"><section className="panel"><div className="panel-head"><h3>Revenue overview</h3><span>Last 7 days</span></div><div className="panel-body"><div className="chart">{[42,58,49,75,62,92,78,96,70,84,66,100].map((h,i)=><div key={i} className="bar" style={{height:`${h}%`}}/>)}</div></div></section><section className="panel"><div className="panel-head"><h3>Recent activity</h3><span>Live</span></div><div className="panel-body"><div className="activity"><Activity a="✦" t="AI resolved 24 conversations" s="8 minutes ago"/><Activity a="▦" t="New product added" s="31 minutes ago"/><Activity a="◫" t="Order #ORD-1048 delivered" s="1 hour ago"/><Activity a="◎" t="WhatsApp connected" s="2 hours ago"/></div></div></section></div><section className="panel table-panel"><div className="panel-head"><h3>Recent orders</h3><span>View all →</span></div><Table/></section></>}
function Stat({l,v,m}:any){return <div className="stat-card"><div className="stat-label">{l}</div><div className="stat-value">{v}</div><div className="stat-meta">↑ {m}</div></div>};function Activity({a,t,s}:any){return <div className="activity-row"><div className="activity-icon">{a}</div><div><b>{t}</b><span>{s}</span></div></div>};function Table(){return <div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o[0]}><td><b>{o[0]}</b></td><td>{o[1]}</td><td>{o[2]}</td><td><span className={`badge badge-${o[4]}`}>{o[3]}</span></td></tr>)}</tbody></table></div>}
function Products(){return <><div className="page-head"><div><h1>Products</h1><p>Manage your catalog and inventory.</p></div><button className="btn btn-primary">+ Add product</button></div><div className="cards-grid">{products.map(p=><article className="product-card" key={p[0]}><div className="product-image">{p[3]}</div><h3>{p[0]}</h3><p>{p[2]}</p><div className="product-price">{p[1]}</div></article>)}</div></>}
function Orders(){return <><div className="page-head"><div><h1>Orders</h1><p>Track every order from first click to delivery.</p></div><input className="search" placeholder="Search orders…"/></div><section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Channel</th></tr></thead><tbody>{orders.map(o=><tr key={o[0]}><td><b>{o[0]}</b></td><td>{o[1]}</td><td>{o[2]}</td><td><span className={`badge badge-${o[4]}`}>{o[3]}</span></td><td>WhatsApp</td></tr>)}</tbody></table></div></section></>}
function Channels(){return <><div className="page-head"><div><h1>Channels</h1><p>Connect the places where your customers talk to you.</p></div></div><div className="setting-grid"><section className="setting-card"><h3>Connected channels</h3><Channel i="W" n="WhatsApp" s="Connected"/><Channel i="f" n="Facebook" s="Ready to connect"/><Channel i="◎" n="Instagram" s="Ready to connect"/><Channel i="T" n="TikTok" s="Coming soon"/></section><section className="setting-card"><h3>AI response policy</h3><div className="notice">Lumia uses your business knowledge and customer context to make responses more relevant.</div><div className="field"><label>Default tone</label><select><option>Helpful & professional</option><option>Friendly & concise</option><option>Sales focused</option></select></div><div className="field"><label>Human handoff</label><select><option>When customer requests a human</option><option>After 3 failed answers</option></select></div></section></div></>}
function Channel({i,n,s}:any){return <div className="channel-card"><div className="channel-left"><div className="channel-icon">{i}</div><div><strong>{n}</strong><small>{s}</small></div></div><span className="toggle">{s==='Connected'?'ACTIVE':'CONNECT'}</span></div>}
function Settings({name}:any){return <><div className="page-head"><div><h1>Settings</h1><p>Control your workspace and business profile.</p></div><button className="btn btn-primary">Save changes</button></div><div className="setting-grid"><section className="setting-card"><h3>Business profile</h3><div className="field"><label>Business name</label><input defaultValue={name} placeholder="My Business"/></div><div className="field"><label>Phone</label><input placeholder="+250 7xx xxx xxx"/></div><div className="field"><label>Address</label><input placeholder="Kigali, Rwanda"/></div></section><section className="setting-card"><h3>Workspace</h3><div className="notice">Your workspace is powered by Lumia AI. Connect channels and add knowledge to improve AI answers.</div><div className="field"><label>Timezone</label><select defaultValue="Africa/Kigali"><option>Africa/Kigali</option><option>Africa/Nairobi</option><option>UTC</option></select></div><div className="field"><label>Business description</label><textarea rows={5} placeholder="Tell Lumia about your business…"/></div></section></div></>}
function Placeholder({title}:any){return <><div className="page-head"><div><h1>{title}</h1><p>This workspace is ready for the next Lumia module.</p></div><button className="btn btn-primary">Get started</button></div><section className="panel"><div className="empty"><strong>{title} is ready</strong><span>Connect this screen to the Lumia API to manage real business data.</span></div></section></>}
